services:
  - type: web
    name: sms
    runtime: python310
    buildCommand: "./build.sh"
    startCommand: "gunicorn sms.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sms_db
          property: connectionString
    autoDeploy: true

databases:
  - name: sms_db
    databaseName: sms_db
    user: sms_user
    region: oregon
